esphome:
  name: nookbook

rp2040:
  board: rpipicow
  framework:
    # Required until https://github.com/platformio/platform-raspberrypi/pull/36 is merged
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

logger:
  level: DEBUG

api:

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret  wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  enable_on_boot: true
  manual_ip:
    static_ip: 192.168.1.203
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 1.1.1.1

output:
  - platform: gpio
    pin:
      number: 25
      mode: output
    id: LED

interval:
  - interval: 500ms
    then:
      - output.turn_on: LED
      - delay: 250ms
      - output.turn_off: LED
