# esphome run
# Number: 
esphome:
  name: model-cafe-c3
  friendly_name: "Model Cafe c3"

esp32:
  board: seeed_xiao_esp32c3
  flash_size: 4MB
  variant: esp32c3

logger:
  level: DEBUG

api:

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret  wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  enable_on_boot: true
  manual_ip:
    static_ip: 192.168.1.206
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 1.1.1.1

light:
  - platform: binary
    name: "LED - 1"
    output: gpo_led

# Use GPIO18 and GND
output:
  - platform: gpio
    pin: 10
    id: gpo_led
